# Generated by Django 3.2.9 on 2021-11-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=128, unique=True)),
                ('u_password', models.CharField(max_length=256)),
                ('u_email', models.EmailField(max_length=254, unique=True)),
                ('u_ticket', models.CharField(max_length=30, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'ordering': ['c_time'],
            },
        ),
    ]
