# Generated by Django 3.2.9 on 2021-11-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='u_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='u_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='u_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='u_ticket',
        ),
    ]
