# Generated by Django 3.2.9 on 2021-11-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
