# Generated by Django 3.2.9 on 2021-11-30 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol1', models.CharField(default='AAPL', max_length=20)),
                ('interval1', models.CharField(choices=[('1day', '1d'), ('1hour', '1h'), ('5mins', '5m'), ('1min', '1m')], default='1d', max_length=5)),
                ('symbol2', models.CharField(default='AAPL', max_length=20)),
                ('interval2', models.CharField(choices=[('1day', '1d'), ('1hour', '1h'), ('5mins', '5m'), ('1min', '1m')], default='5min', max_length=5)),
                ('symbol3', models.CharField(default='AAPL', max_length=20)),
                ('interval3', models.CharField(choices=[('1day', '1d'), ('1hour', '1h'), ('5mins', '5m'), ('1min', '1m')], default='1m', max_length=5)),
                ('keywords', models.TextField(default='stock', max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
