# Generated by Django 3.2.9 on 2021-11-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='interval1',
            field=models.CharField(choices=[('1d', '1day'), ('1h', '1hour'), ('5m', '5mins'), ('1m', '1min')], default='1d', max_length=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='interval2',
            field=models.CharField(choices=[('1d', '1day'), ('1h', '1hour'), ('5m', '5mins'), ('1m', '1min')], default='5min', max_length=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='interval3',
            field=models.CharField(choices=[('1d', '1day'), ('1h', '1hour'), ('5m', '5mins'), ('1m', '1min')], default='1m', max_length=5),
        ),
    ]
