# Generated by Django 3.2.9 on 2021-11-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Due',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Issue',
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
