# Generated by Django 3.2.9 on 2021-11-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211128_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='CompleteStatus',
            new_name='complete_status',
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
